platform :ios ,'8.0'
target ‘App’ do
pod 'AFNetworking', '~> 3.2.1'
pod 'IQKeyboardManager', '~> 4.0.13’
pod 'MBProgressHUD', '~> 1.1.0'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'SDCycleScrollView', '~> 1.75'
pod 'ReactiveCocoa','~>2.1.8'
end

